# 관리자 권한 갖기
sudo: required

#언어(플램폿)선택
language: generic 

#도커 환경 구성
services:
  - docker

#스크립트를 실행할 수 있는 환경
before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t loy124/docker-react-practice -f Dockerfile.dev .

#실행할 스크립트
script:
  - docker run -e CI=true loy124/docker-react-practice npm run test -- --coverage

#테스트 성공 후 
deploy:
  #외부 서비스 표시(s3, elesticbeanstalk, firebase 등등)
  provider: elasticbeanstalk
  #현재 사용하고 있는 AWS의 서비스가 위치하고있는 물리 장소
  region: "ap-northeast-2"
  #생성된 어플리케이션의 이름
  app: "docker-react-app"
  env: "DockerReactApp-env"
  #elasticbeanstalk을 위한 s3 버켓이름
  #travis에서 가지고있는 파일을 압축해서 먼저 s3에 보낸다.
  bucket_name: "elasticbeanstalk-ap-northeast-2-770628485357"
  bucket_path: "docker-react-app"
  #특정 branch에만 해당 aws서버에 올릴 수 있게 설정 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
