version: "3"
services:
  #컨테이너 이름 
  react:
    #현 디렉토리에 있는 Dockerfile 사용  
    build: 
      #도커이미지를 구성하기 위한 파일과 폴더들이 있는 
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    #로컬 머신에 있는 파일을 매핑
    volumes: 
      #app_modules 부분은 /usr/src/app 에 있는것을 사용한다.
      - /usr/src/app/node_modules
      #현재 디렉토리에 있는 부분을 :/usr/src/app 에 매핑한다
      - ./:/usr/src/app
      #윈도우 상에서 자동 적용 부분 
    environment: 
      - CHOKIDAR_USEPOLLING=true
    #리액트 앱을 끌 때 필요
    stdin_open: true
  tests:
    build:
      context: .
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    volumes:
    - /usr/src/app/node_modules
    - ./:/usr/src/app
    command: ["npm", "run", "test"]
    
    